version: '3.7'
services:
  neo4j:
    image: "neo4j"
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    ports:
      - "7474:7474"
      - "7687:7687"
  mysql:
    build:
      context: ../..
      dockerfile: resources/docker/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=rassasy-user
      - MYSQL_PASSWORD=password
    container_name: mysql
    ports:
      - "3306:3306"
